### ISSUE TITLE
request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080

### ISSUE THREAD

**Issue by dianbashuanga** [Chanzhaoyu/chatgpt-web#335]
大佬，我在群晖docker里用sock部署chenzhaoyu94-chatgpt-web，聊天的时候返回“request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080”，请问是啥原因呢？用的SSR.

**Comment by gouguoyin** [comment]
国内接口被墙了，可以使用代理

**Comment by juzi3333** [comment]
用这个试试  https://openapi.ssiic.com

**Comment by l304474555** [comment]
> 用这个试试 https://openapi.ssiic.com

这个可以，感谢

**Comment by jerryzhang721** [comment]
请问https://openapi.ssiic.com/  如何使用啊？

> 用这个试试 https://openapi.ssiic.com

**Comment by juzi3333** [comment]
也是一个用法 修改api的接口就行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 下午4:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080 (Issue #335)





 
请问https://openapi.ssiic.com/  如何使用啊？
  
用这个试试 https://openapi.ssiic.com

**Comment by jerryzhang721** [comment]
> 也是一个用法 修改api的接口就行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月7日(星期二) 下午4:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Chanzhaoyu/chatgpt-web] request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080 (Issue #335) 请问https://openapi.ssiic.com/ 如何使用啊？ 用这个试试 https://openapi.ssiic.com — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬能说具体点吗？

**Comment by juzi3333** [comment]
OPENAI_API_BASE_URL= 'https://openapi.ssiic.com'




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 下午4:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080 (Issue #335)





  
也是一个用法 修改api的接口就行
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年3月7日(星期二) 下午4:23 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Chanzhaoyu/chatgpt-web] request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1080 (Issue #335) 请问https://openapi.ssiic.com/ 如何使用啊？ 用这个试试 https://openapi.ssiic.com — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
大佬能说具体点吗？
